2024-10-07 12:17:44,212 - Internal Server Error: /admin/order/callme/
Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/db/models/options.py", line 676, in get_field
    return self.fields_map[field_name]
KeyError: <function callMe_detail at 0x741fde1f1ea0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 290, in lookup_field
    f = _get_non_gfk_field(opts, name)
  File "/home/aa/.local/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 330, in _get_non_gfk_field
    field = opts.get_field(name)
  File "/home/aa/.local/lib/python3.10/site-packages/django/db/models/options.py", line 678, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: CallMe has no field named '<function callMe_detail at 0x741fde1f1ea0>'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/contrib/admin/templatetags/base.py", line 45, in render
    return super().render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/home/aa/.local/lib/python3.10/site-packages/django/contrib/admin/templatetags/admin_list.py", line 346, in result_list
    "results": list(results(cl)),
  File "/home/aa/.local/lib/python3.10/site-packages/django/contrib/admin/templatetags/admin_list.py", line 322, in results
    yield ResultList(None, items_for_result(cl, res, None))
  File "/home/aa/.local/lib/python3.10/site-packages/django/contrib/admin/templatetags/admin_list.py", line 313, in __init__
    super().__init__(*items)
  File "/home/aa/.local/lib/python3.10/site-packages/django/contrib/admin/templatetags/admin_list.py", line 218, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
  File "/home/aa/.local/lib/python3.10/site-packages/django/contrib/admin/utils.py", line 296, in lookup_field
    value = attr(obj)
  File "/media/aa/A/rg/order/admin.py", line 8, in callMe_detail
    url = reverse('order:admin_callMe_detail', args=[obj.id])
  File "/home/aa/.local/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/aa/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'admin_callMe_detail' not found. 'admin_callMe_detail' is not a valid view function or pattern name.
2024-10-07 12:17:44,325 - Not Found: /favicon.ico
2024-10-07 12:22:17,356 - /media/aa/A/rg/order/views.py changed, reloading.
2024-10-07 12:22:37,481 - /media/aa/A/rg/order/views.py changed, reloading.
2024-10-07 12:23:14,759 - /media/aa/A/rg/order/views.py changed, reloading.
2024-10-07 12:23:39,728 - /media/aa/A/rg/order/urls.py changed, reloading.
2024-10-07 12:23:46,615 - Not Found: /admin/order/2/
2024-10-07 12:27:32,666 - Not Found: /favicon.ico
2024-10-07 12:27:34,180 - Not Found: /admin/order/3/
2024-10-07 12:29:04,893 - Not Found: /admin/order/2/
2024-10-07 12:36:09,017 - /media/aa/A/rg/order/urls.py changed, reloading.
2024-10-07 12:36:13,927 - /media/aa/A/rg/order/urls.py changed, reloading.
2024-10-07 12:36:17,028 - Not Found: /admin/order/2/
2024-10-07 12:36:17,142 - Not Found: /favicon.ico
2024-10-07 12:36:20,881 - Not Found: /favicon.ico
2024-10-07 12:36:24,285 - Not Found: /admin/callme/3/
2024-10-07 12:37:09,033 - /media/aa/A/rg/order/admin.py changed, reloading.
2024-10-07 12:37:13,082 - Not Found: /favicon.ico
2024-10-07 12:38:16,421 - /media/aa/A/rg/order/admin.py changed, reloading.
2024-10-07 12:38:25,388 - /media/aa/A/rg/order/admin.py changed, reloading.
2024-10-07 12:38:28,465 - Not Found: /favicon.ico
2024-10-07 12:38:48,794 - /media/aa/A/rg/order/admin.py changed, reloading.
2024-10-07 12:38:53,596 - /media/aa/A/rg/order/admin.py changed, reloading.
2024-10-07 12:39:14,707 - /media/aa/A/rg/order/admin.py changed, reloading.
2024-10-07 12:39:18,473 - /media/aa/A/rg/order/admin.py changed, reloading.
2024-10-07 12:39:34,882 - Not Found: /favicon.ico
2024-10-07 12:39:51,255 - /media/aa/A/rg/order/admin.py changed, reloading.
2024-10-07 12:40:13,784 - /media/aa/A/rg/order/admin.py changed, reloading.
2024-10-07 12:41:18,866 - /media/aa/A/rg/order/views.py changed, reloading.
2024-10-07 12:41:43,417 - Not Found: /favicon.ico
2024-10-07 12:42:11,853 - /media/aa/A/rg/order/urls.py changed, reloading.
2024-10-07 12:42:16,623 - /media/aa/A/rg/order/urls.py changed, reloading.
2024-10-07 12:42:24,398 - /media/aa/A/rg/order/views.py changed, reloading.
2024-10-07 12:43:14,874 - /media/aa/A/rg/order/views.py changed, reloading.
2024-10-07 12:43:17,625 - /media/aa/A/rg/order/views.py changed, reloading.
2024-10-07 12:43:21,371 - Not Found: /favicon.ico
2024-10-07 12:43:47,054 - /media/aa/A/rg/order/urls.py changed, reloading.
2024-10-07 12:44:41,909 - /media/aa/A/rg/order/admin.py changed, reloading.
2024-10-07 12:46:35,141 - Not Found: /favicon.ico
2024-10-07 12:46:37,865 - Not Found: /favicon.ico
2024-10-07 12:47:13,997 - /media/aa/A/rg/order/admin.py changed, reloading.
2024-10-07 12:47:46,398 - /media/aa/A/rg/order/admin.py changed, reloading.
2024-10-07 12:47:51,209 - /media/aa/A/rg/order/views.py changed, reloading.
2024-10-07 12:48:18,464 - /media/aa/A/rg/order/urls.py changed, reloading.
2024-10-07 12:48:49,840 - /media/aa/A/rg/order/views.py changed, reloading.
2024-10-07 12:48:57,938 - Not Found: /favicon.ico
2024-10-07 12:49:20,548 - /media/aa/A/rg/order/admin.py changed, reloading.
2024-10-07 12:49:26,583 - Not Found: /admin/callme/3/
2024-10-07 12:49:59,584 - /media/aa/A/rg/order/urls.py changed, reloading.
2024-10-07 12:50:01,705 - Not Found: /favicon.ico
2024-10-07 12:50:03,163 - Not Found: /favicon.ico
2024-10-07 12:50:09,443 - Not Found: /favicon.ico
2024-10-07 12:51:21,106 - Not Found: /favicon.ico
2024-10-07 12:54:56,406 - /media/aa/A/rg/order/admin.py changed, reloading.
2024-10-07 13:04:20,334 - /media/aa/A/rg/order/views.py changed, reloading.
2024-10-07 13:04:43,301 - /media/aa/A/rg/order/admin.py changed, reloading.
2024-10-07 13:07:04,725 - /media/aa/A/rg/order/views.py changed, reloading.
2024-10-07 13:08:45,733 - /media/aa/A/rg/order/admin.py changed, reloading.
2024-10-07 13:12:51,524 - /media/aa/A/rg/order/models.py changed, reloading.
2024-10-07 13:13:42,530 - /media/aa/A/rg/order/models.py changed, reloading.
2024-10-07 13:14:04,314 - /media/aa/A/rg/order/admin.py changed, reloading.
2024-10-07 13:14:20,242 - /media/aa/A/rg/order/admin.py changed, reloading.
2024-10-07 13:15:05,931 - /media/aa/A/rg/order/admin.py changed, reloading.
2024-10-07 13:15:17,777 - /media/aa/A/rg/order/admin.py changed, reloading.
2024-10-07 13:15:40,911 - /media/aa/A/rg/order/admin.py changed, reloading.
2024-10-07 13:16:26,000 - /media/aa/A/rg/order/admin.py changed, reloading.
2024-10-07 13:16:33,812 - /media/aa/A/rg/order/admin.py changed, reloading.
2024-10-07 14:26:22,801 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 14:27:01,288 - /media/aa/A/rg/order/models.py changed, reloading.
2024-10-07 14:27:26,429 - /media/aa/A/rg/order/forms.py changed, reloading.
2024-10-07 14:29:18,339 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 14:29:36,410 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 14:38:51,590 - /media/aa/A/rg/order/forms.py changed, reloading.
2024-10-07 14:39:26,963 - /media/aa/A/rg/order/views.py changed, reloading.
2024-10-07 14:40:08,482 - /media/aa/A/rg/order/views.py changed, reloading.
2024-10-07 14:40:40,838 - /media/aa/A/rg/order/views.py changed, reloading.
2024-10-07 14:41:05,957 - /media/aa/A/rg/order/views.py changed, reloading.
2024-10-07 14:44:07,139 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 14:50:49,503 - /media/aa/A/rg/order/models.py changed, reloading.
2024-10-07 14:51:21,828 - /media/aa/A/rg/cars/views.py changed, reloading.
2024-10-07 14:51:32,003 - Internal Server Error: /4/
Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/aa/A/rg/cars/views.py", line 75, in the_car
    want_this_car_form = handle_want_this_car_form(request)
  File "/media/aa/A/rg/cars/forms_generator.py", line 28, in handle_want_this_car_form
    if form.is_valid():
NameError: name 'form' is not defined
2024-10-07 14:51:55,419 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 14:52:23,169 - Not Found: /favicon.ico
2024-10-07 16:03:52,953 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 16:05:33,225 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 16:08:34,418 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 16:08:53,367 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 16:09:32,821 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 16:10:39,399 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 16:10:42,183 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 16:11:30,810 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 16:12:13,342 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 16:13:23,418 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 16:14:01,812 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 16:17:30,679 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 16:18:50,895 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 16:19:24,203 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 16:20:08,687 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 16:20:39,898 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 16:21:08,996 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 16:23:10,064 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 16:23:34,211 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 16:24:12,602 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 16:28:01,479 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 16:38:49,822 - Not Found: /favicon.ico
2024-10-07 16:40:42,846 - /media/aa/A/rg/cars/views.py changed, reloading.
2024-10-07 16:43:28,391 - Internal Server Error: /14/
Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/aa/A/rg/cars/views.py", line 75, in the_car
    want_this_car = handle_want_this_car_form(request)
  File "/media/aa/A/rg/cars/forms_generator.py", line 36, in handle_want_this_car_form
    car_name=car_name
NameError: name 'car_name' is not defined
2024-10-07 16:46:46,839 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 16:46:53,341 - Internal Server Error: /14/
Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/aa/A/rg/cars/views.py", line 75, in the_car
    want_this_car = handle_want_this_car_form(request)
  File "/media/aa/A/rg/cars/forms_generator.py", line 37, in handle_want_this_car_form
    car_name=car_name
NameError: name 'car_name' is not defined
2024-10-07 16:47:24,370 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 16:47:28,993 - Internal Server Error: /14/
Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/aa/A/rg/cars/views.py", line 75, in the_car
    want_this_car = handle_want_this_car_form(request)
  File "/media/aa/A/rg/cars/forms_generator.py", line 34, in handle_want_this_car_form
    want_this_car = WantThisCarForm(
TypeError: BaseForm.__init__() got an unexpected keyword argument 'first_name'
2024-10-07 16:47:38,473 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 16:47:58,138 - Internal Server Error: /14/
Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/aa/A/rg/cars/views.py", line 75, in the_car
    want_this_car = handle_want_this_car_form(request)
  File "/media/aa/A/rg/cars/forms_generator.py", line 34, in handle_want_this_car_form
    want_this_car = WantThisCarForm(
TypeError: BaseForm.__init__() got an unexpected keyword argument 'first_name'
2024-10-07 16:54:29,138 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 16:54:35,956 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 16:55:04,460 - Internal Server Error: /14/
Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/aa/A/rg/cars/views.py", line 75, in the_car
    want_this_car = handle_want_this_car_form(request)
  File "/media/aa/A/rg/cars/forms_generator.py", line 34, in handle_want_this_car_form
    want_this_car = WantThisCarForm(
TypeError: BaseForm.__init__() got an unexpected keyword argument 'first_name'
2024-10-07 16:57:10,522 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 16:57:34,141 - Internal Server Error: /5/
Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/aa/A/rg/cars/views.py", line 75, in the_car
    want_this_car = handle_want_this_car_form(request)
  File "/media/aa/A/rg/cars/forms_generator.py", line 34, in handle_want_this_car_form
    want_this_car = WantThisCarForm(
TypeError: BaseForm.__init__() got an unexpected keyword argument 'first_name'
2024-10-07 16:58:54,681 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 16:59:12,926 - Internal Server Error: /5/
Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/aa/A/rg/cars/views.py", line 75, in the_car
    want_this_car = handle_want_this_car_form(request)
  File "/media/aa/A/rg/cars/forms_generator.py", line 34, in handle_want_this_car_form
    want_this_car = WantThisCarForm(
TypeError: BaseForm.__init__() got an unexpected keyword argument 'first_name'
2024-10-07 17:01:58,444 - Internal Server Error: /2/
Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/aa/A/rg/cars/views.py", line 75, in the_car
    want_this_car = handle_want_this_car_form(request)
  File "/media/aa/A/rg/cars/forms_generator.py", line 34, in handle_want_this_car_form
    want_this_car = WantThisCarForm(
TypeError: BaseForm.__init__() got an unexpected keyword argument 'first_name'
2024-10-07 17:19:44,299 - Internal Server Error: /2/
Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/aa/A/rg/cars/views.py", line 75, in the_car
    want_this_car = handle_want_this_car_form(request)
  File "/media/aa/A/rg/cars/forms_generator.py", line 34, in handle_want_this_car_form
    want_this_car = WantThisCarForm(
TypeError: BaseForm.__init__() got an unexpected keyword argument 'first_name'
2024-10-07 17:27:00,865 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 17:27:06,351 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 17:27:21,130 - /media/aa/A/rg/order/forms.py changed, reloading.
2024-10-07 17:27:24,882 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 17:27:25,066 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 17:27:31,432 - Internal Server Error: /6/
Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/aa/A/rg/cars/views.py", line 75, in the_car
    want_this_car = handle_want_this_car_form(request)
  File "/media/aa/A/rg/cars/forms_generator.py", line 34, in handle_want_this_car_form
    want_this_car = WantThisCarForm(
TypeError: BaseForm.__init__() got an unexpected keyword argument 'first_name'
2024-10-07 17:30:35,290 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 17:40:51,323 - /media/aa/A/rg/order/tasks.py changed, reloading.
2024-10-07 17:41:12,492 - /media/aa/A/rg/order/tasks.py changed, reloading.
2024-10-07 17:41:22,163 - Internal Server Error: /6/
Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/aa/A/rg/cars/views.py", line 75, in the_car
    want_this_car = handle_want_this_car_form(request)
  File "/media/aa/A/rg/cars/forms_generator.py", line 34, in handle_want_this_car_form
    want_this_car = WantThisCarForm(
TypeError: BaseForm.__init__() got an unexpected keyword argument 'first_name'
2024-10-07 17:42:11,744 - /media/aa/A/rg/order/tasks.py changed, reloading.
2024-10-07 20:17:58,887 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 20:18:06,915 - Internal Server Error: /4/
Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/aa/A/rg/cars/views.py", line 75, in the_car
    want_this_car = handle_want_this_car_form(request)
  File "/media/aa/A/rg/cars/forms_generator.py", line 34, in handle_want_this_car_form
    want_this_car = WantThisCarForm(
TypeError: BaseForm.__init__() got an unexpected keyword argument 'first_name'
2024-10-07 20:18:50,148 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 20:19:37,219 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-07 20:30:24,369 - Internal Server Error: /23/
Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/aa/A/rg/cars/views.py", line 83, in the_car
    return render(request, 'cars/the_car.html', context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/engine.py", line 208, in select_template
    return self.get_template(template_name)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 573, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 10: 'static'. Did you forget to register or load this tag?
2024-10-07 20:36:33,006 - Internal Server Error: /23/
Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/aa/A/rg/cars/views.py", line 83, in the_car
    return render(request, 'cars/the_car.html', context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/engine.py", line 208, in select_template
    return self.get_template(template_name)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 573, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 19: 'static'. Did you forget to register or load this tag?
2024-10-07 20:37:18,507 - Internal Server Error: /23/
Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/aa/A/rg/cars/views.py", line 83, in the_car
    return render(request, 'cars/the_car.html', context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/engine.py", line 208, in select_template
    return self.get_template(template_name)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 573, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 19: 'static'. Did you forget to register or load this tag?
2024-10-07 20:37:18,620 - Not Found: /favicon.ico
2024-10-07 20:37:37,808 - Not Found: /media/Volkswagen_Terramont_Х_1.jpg
2024-10-07 20:37:37,823 - Not Found: /media/Volkswagen_Terramont_Х_2.jpg
2024-10-07 20:37:37,831 - Not Found: /media/Volkswagen_Terramont_Х_3.jpg
2024-10-07 20:37:37,843 - Not Found: /media/Volkswagen_Terramont_Х_4.jpg
2024-10-07 20:37:37,862 - Not Found: /media/Volkswagen_Terramont_Х_5.jpg
2024-10-07 20:37:37,866 - Not Found: /media/Volkswagen_Terramont_Х_6.jpg
2024-10-07 20:37:37,898 - Not Found: /media/Volkswagen_Terramont_Х_9.jpg
2024-10-07 20:37:37,915 - Not Found: /media/Volkswagen_Terramont_Х_10.jpg
2024-10-07 20:37:37,924 - Not Found: /media/Volkswagen_Terramont_Х_8.jpg
2024-10-07 20:37:37,944 - Not Found: /media/Volkswagen_Terramont_Х_7.jpg
2024-10-07 20:37:38,112 - Not Found: /media/Volkswagen_Terramont_Х_1.jpg
2024-10-07 20:37:38,150 - Not Found: /media/Volkswagen_Terramont_Х_3.jpg
2024-10-07 20:37:38,162 - Not Found: /media/Volkswagen_Terramont_Х_2.jpg
2024-10-07 20:37:38,170 - Not Found: /media/Volkswagen_Terramont_Х_6.jpg
2024-10-07 20:37:38,180 - Not Found: /media/Volkswagen_Terramont_Х_7.jpg
2024-10-07 20:37:38,185 - Not Found: /media/Volkswagen_Terramont_Х_5.jpg
2024-10-07 20:37:38,197 - Not Found: /media/Volkswagen_Terramont_Х_4.jpg
2024-10-07 20:37:38,200 - Not Found: /media/Volkswagen_Terramont_Х_8.jpg
2024-10-07 20:37:38,222 - Not Found: /media/Volkswagen_Terramont_Х_10.jpg
2024-10-07 20:37:38,223 - Not Found: /media/Volkswagen_Terramont_Х_9.jpg
2024-10-07 20:38:21,225 - Not Found: /media/Volkswagen_Terramont_Х_5.jpg
2024-10-07 20:38:21,233 - Not Found: /media/Volkswagen_Terramont_Х_3.jpg
2024-10-07 20:38:21,247 - Not Found: /media/Volkswagen_Terramont_Х_2.jpg
2024-10-07 20:38:21,247 - Not Found: /media/Volkswagen_Terramont_Х_4.jpg
2024-10-07 20:38:21,254 - Not Found: /media/Volkswagen_Terramont_Х_1.jpg
2024-10-07 20:38:21,262 - Not Found: /media/Volkswagen_Terramont_Х_6.jpg
2024-10-07 20:38:21,273 - Not Found: /media/Volkswagen_Terramont_Х_8.jpg
2024-10-07 20:38:21,297 - Not Found: /media/Volkswagen_Terramont_Х_7.jpg
2024-10-07 20:38:21,301 - Not Found: /media/Volkswagen_Terramont_Х_9.jpg
2024-10-07 20:38:21,310 - Not Found: /media/Volkswagen_Terramont_Х_10.jpg
2024-10-07 20:38:21,371 - Not Found: /media/Volkswagen_Terramont_Х_1.jpg
2024-10-07 20:38:21,386 - Not Found: /media/Volkswagen_Terramont_Х_5.jpg
2024-10-07 20:38:21,389 - Not Found: /media/Volkswagen_Terramont_Х_3.jpg
2024-10-07 20:38:21,400 - Not Found: /media/Volkswagen_Terramont_Х_4.jpg
2024-10-07 20:38:21,402 - Not Found: /media/Volkswagen_Terramont_Х_2.jpg
2024-10-07 20:38:21,409 - Not Found: /media/Volkswagen_Terramont_Х_6.jpg
2024-10-07 20:38:21,419 - Not Found: /media/Volkswagen_Terramont_Х_7.jpg
2024-10-07 20:38:21,434 - Not Found: /media/Volkswagen_Terramont_Х_8.jpg
2024-10-07 20:38:30,314 - Not Found: /media/Volkswagen_Terramont_Х_6.jpg
2024-10-07 20:38:30,327 - Not Found: /media/Volkswagen_Terramont_Х_1.jpg
2024-10-07 20:38:30,339 - Not Found: /media/Volkswagen_Terramont_Х_2.jpg
2024-10-07 20:38:30,355 - Not Found: /media/Volkswagen_Terramont_Х_3.jpg
2024-10-07 20:38:30,371 - Not Found: /media/Volkswagen_Terramont_Х_5.jpg
2024-10-07 20:38:30,373 - Not Found: /media/Volkswagen_Terramont_Х_4.jpg
2024-10-07 20:38:30,383 - Not Found: /media/Volkswagen_Terramont_Х_7.jpg
2024-10-07 20:38:30,398 - Not Found: /media/Volkswagen_Terramont_Х_8.jpg
2024-10-07 20:38:30,407 - Not Found: /media/Volkswagen_Terramont_Х_9.jpg
2024-10-07 20:38:30,415 - Not Found: /media/Volkswagen_Terramont_Х_10.jpg
2024-10-07 20:39:12,806 - Not Found: /media/Volkswagen_Terramont_Х_3.jpg
2024-10-07 20:39:12,817 - Not Found: /media/Volkswagen_Terramont_Х_6.jpg
2024-10-07 20:39:12,818 - Not Found: /media/Volkswagen_Terramont_Х_2.jpg
2024-10-07 20:39:12,818 - Not Found: /media/Volkswagen_Terramont_Х_4.jpg
2024-10-07 20:39:12,831 - Not Found: /media/Volkswagen_Terramont_Х_5.jpg
2024-10-07 20:39:12,832 - Not Found: /media/Volkswagen_Terramont_Х_1.jpg
2024-10-07 20:39:12,842 - Not Found: /media/Volkswagen_Terramont_Х_7.jpg
2024-10-07 20:39:12,855 - Not Found: /media/Volkswagen_Terramont_Х_8.jpg
2024-10-07 20:39:12,882 - Not Found: /media/Volkswagen_Terramont_Х_9.jpg
2024-10-07 20:39:12,884 - Not Found: /media/Volkswagen_Terramont_Х_10.jpg
2024-10-07 20:39:13,077 - Not Found: /media/Volkswagen_Terramont_Х_2.jpg
2024-10-07 20:39:13,084 - Not Found: /media/Volkswagen_Terramont_Х_1.jpg
2024-10-07 20:39:13,096 - Not Found: /media/Volkswagen_Terramont_Х_4.jpg
2024-10-07 20:39:13,100 - Not Found: /media/Volkswagen_Terramont_Х_3.jpg
2024-10-07 20:39:13,107 - Not Found: /media/Volkswagen_Terramont_Х_6.jpg
2024-10-07 20:39:13,114 - Not Found: /media/Volkswagen_Terramont_Х_5.jpg
2024-10-07 20:39:13,131 - Not Found: /media/Volkswagen_Terramont_Х_7.jpg
2024-10-07 20:39:13,135 - Not Found: /media/Volkswagen_Terramont_Х_8.jpg
2024-10-07 20:39:13,145 - Not Found: /media/Volkswagen_Terramont_Х_9.jpg
2024-10-07 20:39:13,153 - Not Found: /media/Volkswagen_Terramont_Х_10.jpg
2024-10-07 20:41:15,363 - Not Found: /media/Volkswagen_Terramont_Х_1.jpg
2024-10-07 20:41:15,374 - Not Found: /media/Volkswagen_Terramont_Х_5.jpg
2024-10-07 20:41:15,386 - Not Found: /media/Volkswagen_Terramont_Х_6.jpg
2024-10-07 20:41:15,387 - Not Found: /media/Volkswagen_Terramont_Х_4.jpg
2024-10-07 20:41:15,390 - Not Found: /media/Volkswagen_Terramont_Х_3.jpg
2024-10-07 20:41:15,393 - Not Found: /media/Volkswagen_Terramont_Х_2.jpg
2024-10-07 20:41:15,405 - Not Found: /media/Volkswagen_Terramont_Х_8.jpg
2024-10-07 20:41:15,418 - Not Found: /media/Volkswagen_Terramont_Х_7.jpg
2024-10-07 20:41:15,425 - Not Found: /media/Volkswagen_Terramont_Х_9.jpg
2024-10-07 20:41:15,434 - Not Found: /media/Volkswagen_Terramont_Х_10.jpg
2024-10-07 20:41:15,745 - Not Found: /media/Volkswagen_Terramont_Х_1.jpg
2024-10-07 20:41:15,763 - Not Found: /media/Volkswagen_Terramont_Х_2.jpg
2024-10-07 20:41:15,763 - Not Found: /media/Volkswagen_Terramont_Х_3.jpg
2024-10-07 20:41:15,769 - Not Found: /media/Volkswagen_Terramont_Х_4.jpg
2024-10-07 20:41:15,777 - Not Found: /media/Volkswagen_Terramont_Х_5.jpg
2024-10-07 20:41:15,788 - Not Found: /media/Volkswagen_Terramont_Х_6.jpg
2024-10-07 20:41:15,795 - Not Found: /media/Volkswagen_Terramont_Х_7.jpg
2024-10-07 20:41:15,801 - Not Found: /media/Volkswagen_Terramont_Х_8.jpg
2024-10-07 20:41:15,811 - Not Found: /media/Volkswagen_Terramont_Х_9.jpg
2024-10-07 20:41:15,819 - Not Found: /media/Volkswagen_Terramont_Х_10.jpg
2024-10-07 20:41:34,915 - Not Found: /media/Volkswagen_Terramont_Х_1.jpg
2024-10-07 20:41:34,922 - Not Found: /media/Volkswagen_Terramont_Х_2.jpg
2024-10-07 20:41:34,929 - Not Found: /media/Volkswagen_Terramont_Х_3.jpg
2024-10-07 20:41:34,973 - Not Found: /media/Volkswagen_Terramont_Х_6.jpg
2024-10-07 20:41:34,975 - Not Found: /media/Volkswagen_Terramont_Х_4.jpg
2024-10-07 20:41:34,978 - Not Found: /media/Volkswagen_Terramont_Х_5.jpg
2024-10-07 20:41:34,988 - Not Found: /media/Volkswagen_Terramont_Х_10.jpg
2024-10-07 20:41:34,994 - Not Found: /media/Volkswagen_Terramont_Х_9.jpg
2024-10-07 20:41:35,051 - Not Found: /media/Volkswagen_Terramont_Х_7.jpg
2024-10-07 20:41:35,063 - Not Found: /media/Volkswagen_Terramont_Х_8.jpg
2024-10-07 20:41:35,629 - Not Found: /media/Volkswagen_Terramont_Х_1.jpg
2024-10-07 20:41:35,638 - Not Found: /media/Volkswagen_Terramont_Х_2.jpg
2024-10-07 20:41:35,653 - Not Found: /media/Volkswagen_Terramont_Х_3.jpg
2024-10-07 20:41:35,654 - Not Found: /media/Volkswagen_Terramont_Х_5.jpg
2024-10-07 20:41:35,664 - Not Found: /media/Volkswagen_Terramont_Х_4.jpg
2024-10-07 20:41:35,669 - Not Found: /media/Volkswagen_Terramont_Х_6.jpg
2024-10-07 20:41:35,682 - Not Found: /media/Volkswagen_Terramont_Х_7.jpg
2024-10-07 20:41:35,689 - Not Found: /media/Volkswagen_Terramont_Х_8.jpg
2024-10-07 20:41:35,697 - Not Found: /media/Volkswagen_Terramont_Х_9.jpg
2024-10-07 20:41:35,705 - Not Found: /media/Volkswagen_Terramont_Х_10.jpg
2024-10-07 20:41:45,683 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 20:41:45,896 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 20:43:10,363 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 20:43:10,537 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 20:43:24,302 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 20:43:24,602 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 20:43:33,199 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 20:43:33,381 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 20:44:02,054 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 20:44:02,188 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 20:44:07,632 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 20:44:23,581 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 20:44:23,732 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 20:44:35,045 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 20:44:35,198 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 20:44:41,500 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 20:44:41,630 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 20:47:35,312 - Internal Server Error: /6/
Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/engine.py", line 214, in select_template
    raise TemplateDoesNotExist(", ".join(not_found))
django.template.exceptions.TemplateDoesNotExist: cars/popups/banner_want_similar.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/aa/A/rg/cars/views.py", line 83, in the_car
    return render(request, 'cars/the_car.html', context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 109, in render
    reraise(exc, self.backend)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: cars/popups/banner_want_similar.html
2024-10-07 20:47:55,999 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 20:47:56,152 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 20:48:31,866 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 20:48:31,990 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 20:48:47,077 - Internal Server Error: /6/
Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/engine.py", line 214, in select_template
    raise TemplateDoesNotExist(", ".join(not_found))
django.template.exceptions.TemplateDoesNotExist: cars/popups/search_auto.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/aa/A/rg/cars/views.py", line 83, in the_car
    return render(request, 'cars/the_car.html', context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 109, in render
    reraise(exc, self.backend)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: cars/popups/search_auto.html
2024-10-07 20:49:13,936 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 20:49:14,091 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 20:49:44,018 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 20:49:44,200 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 20:50:46,859 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 20:50:46,961 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 20:50:48,450 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 20:50:48,590 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 20:51:24,391 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-07 20:51:24,571 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-08 13:54:29,156 - Not Found: /favicon.ico
2024-10-08 13:58:48,255 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-08 13:59:35,371 - /media/aa/A/rg/rg/settings.py changed, reloading.
2024-10-08 13:59:51,655 - Not Found: /favicon.ico
2024-10-08 14:43:32,209 - /media/aa/A/rg/order/views.py changed, reloading.
2024-10-08 14:46:24,493 - /media/aa/A/rg/order/views.py changed, reloading.
2024-10-08 15:07:50,614 - /media/aa/A/rg/order/views.py changed, reloading.
2024-10-08 15:49:39,513 - /media/aa/A/rg/order/models.py changed, reloading.
2024-10-08 15:50:31,394 - /media/aa/A/rg/order/models.py changed, reloading.
2024-10-08 15:51:19,046 - /media/aa/A/rg/order/views.py changed, reloading.
2024-10-08 15:51:42,207 - /media/aa/A/rg/order/views.py changed, reloading.
2024-10-08 15:51:50,880 - Not Found: /media/cars/Kia_K5_Gt_line_8.jpg
2024-10-08 15:51:50,891 - Not Found: /media/cars/Kia_K5_Gt_line_9.jpg
2024-10-08 15:51:50,903 - Not Found: /media/cars/Kia_K5_Gt_line_10.jpg
2024-10-08 15:51:51,236 - Not Found: /media/cars/Kia_K5_Gt_line_8.jpg
2024-10-08 15:51:51,255 - Not Found: /media/cars/Kia_K5_Gt_line_10.jpg
2024-10-08 15:51:51,247 - Not Found: /media/cars/Kia_K5_Gt_line_9.jpg
2024-10-08 15:51:56,473 - Not Found: /media/cars/Kia_K5_Gt_line_8.jpg
2024-10-08 15:51:56,476 - Not Found: /media/cars/Kia_K5_Gt_line_10.jpg
2024-10-08 15:51:56,484 - Not Found: /media/cars/Kia_K5_Gt_line_9.jpg
2024-10-08 15:51:56,674 - Not Found: /media/cars/Kia_K5_Gt_line_9.jpg
2024-10-08 15:51:56,676 - Not Found: /media/cars/Kia_K5_Gt_line_8.jpg
2024-10-08 15:51:56,682 - Not Found: /media/cars/Kia_K5_Gt_line_10.jpg
2024-10-08 15:53:41,044 - Not Found: /favicon.ico
2024-10-08 15:53:42,450 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-08 15:53:42,793 - Not Found: /media/cars/Audi_A7L_black_10.jpg
2024-10-08 15:54:05,322 - Not Found: /media/cars/Audi_A8L_black_10.jpg
2024-10-08 15:54:05,719 - Not Found: /media/cars/Audi_A8L_black_10.jpg
2024-10-08 15:54:28,647 - Not Found: /media/cars/Exeed_RX_7.jpg
2024-10-08 15:54:28,659 - Not Found: /media/cars/Exeed_RX_8.jpg
2024-10-08 15:54:28,671 - Not Found: /media/cars/Exeed_RX_9.jpg
2024-10-08 15:54:28,677 - Not Found: /media/cars/Exeed_RX_10.jpg
2024-10-08 15:54:29,135 - Not Found: /media/cars/Exeed_RX_7.jpg
2024-10-08 15:54:29,139 - Not Found: /media/cars/Exeed_RX_9.jpg
2024-10-08 15:54:29,148 - Not Found: /media/cars/Exeed_RX_10.jpg
2024-10-08 15:54:29,155 - Not Found: /media/cars/Exeed_RX_8.jpg
2024-10-08 15:55:15,641 - Not Found: /media/cars/ KIA_KX3_white_10.jpg
2024-10-08 15:55:16,039 - Not Found: /media/cars/ KIA_KX3_white_10.jpg
2024-10-08 15:55:37,886 - Not Found: /media/cars/Kia_K5_Gt_line_10.jpg
2024-10-08 15:55:37,894 - Not Found: /media/cars/Kia_K5_Gt_line_9.jpg
2024-10-08 15:55:37,897 - Not Found: /media/cars/Kia_K5_Gt_line_8.jpg
2024-10-08 15:55:38,142 - Not Found: /media/cars/Kia_K5_Gt_line_9.jpg
2024-10-08 15:55:38,154 - Not Found: /media/cars/Kia_K5_Gt_line_8.jpg
2024-10-08 15:55:38,157 - Not Found: /media/cars/Kia_K5_Gt_line_10.jpg
2024-10-08 15:55:56,097 - Not Found: /media/cars/KIA_Pegas_01.jpg
2024-10-08 15:55:56,372 - Not Found: /media/cars/KIA_Pegas_01.jpg
2024-10-08 15:56:47,144 - Not Found: /media/cars/Mitsubishi_Outlander_9.jpg
2024-10-08 15:56:47,179 - Not Found: /media/cars/Mitsubishi_Outlander_10.jpg
2024-10-08 15:56:47,662 - Not Found: /media/cars/Mitsubishi_Outlander_9.jpg
2024-10-08 15:56:47,668 - Not Found: /media/cars/Mitsubishi_Outlander_10.jpg
2024-10-08 15:57:07,250 - Not Found: /media/cars/Toyota_Corolla_silver_10.jpg
2024-10-08 15:57:07,257 - Not Found: /media/cars/Toyota_Corolla_silver_9.jpg
2024-10-08 15:57:07,553 - Not Found: /media/cars/Toyota_Corolla_silver_10.jpg
2024-10-08 15:57:07,563 - Not Found: /media/cars/Toyota_Corolla_silver_9.jpg
2024-10-08 15:57:22,173 - Not Found: /media/cars/Toyota_RAV4_7.jpg
2024-10-08 15:57:22,189 - Not Found: /media/cars/Toyota_RAV4_6.jpg
2024-10-08 15:57:22,198 - Not Found: /media/cars/Toyota_RAV4_8.jpg
2024-10-08 15:57:22,209 - Not Found: /media/cars/Toyota_RAV4_9.jpg
2024-10-08 15:57:22,222 - Not Found: /media/cars/Toyota_RAV4_10.jpg
2024-10-08 15:57:22,588 - Not Found: /media/cars/Toyota_RAV4_6.jpg
2024-10-08 15:57:22,596 - Not Found: /media/cars/Toyota_RAV4_9.jpg
2024-10-08 15:57:22,613 - Not Found: /media/cars/Toyota_RAV4_10.jpg
2024-10-08 15:57:22,615 - Not Found: /media/cars/Toyota_RAV4_7.jpg
2024-10-08 15:57:22,627 - Not Found: /media/cars/Toyota_RAV4_8.jpg
2024-10-08 15:57:45,102 - Not Found: /media/Volkswagen_Terramont_Х_1.jpg
2024-10-08 15:57:45,148 - Not Found: /media/Volkswagen_Terramont_Х_2.jpg
2024-10-08 15:57:45,150 - Not Found: /media/Volkswagen_Terramont_Х_7.jpg
2024-10-08 15:57:45,157 - Not Found: /media/Volkswagen_Terramont_Х_4.jpg
2024-10-08 15:57:45,170 - Not Found: /media/Volkswagen_Terramont_Х_6.jpg
2024-10-08 15:57:45,172 - Not Found: /media/Volkswagen_Terramont_Х_3.jpg
2024-10-08 15:57:45,180 - Not Found: /media/Volkswagen_Terramont_Х_5.jpg
2024-10-08 15:57:45,195 - Not Found: /media/Volkswagen_Terramont_Х_8.jpg
2024-10-08 15:57:45,206 - Not Found: /media/Volkswagen_Terramont_Х_9.jpg
2024-10-08 15:57:45,212 - Not Found: /media/Volkswagen_Terramont_Х_10.jpg
2024-10-08 15:57:45,359 - Not Found: /media/Volkswagen_Terramont_Х_1.jpg
2024-10-08 15:57:45,365 - Not Found: /media/Volkswagen_Terramont_Х_2.jpg
2024-10-08 15:57:45,373 - Not Found: /media/Volkswagen_Terramont_Х_5.jpg
2024-10-08 15:57:45,382 - Not Found: /media/Volkswagen_Terramont_Х_6.jpg
2024-10-08 15:57:45,394 - Not Found: /media/Volkswagen_Terramont_Х_4.jpg
2024-10-08 15:57:45,397 - Not Found: /media/Volkswagen_Terramont_Х_3.jpg
2024-10-08 15:57:45,419 - Not Found: /media/Volkswagen_Terramont_Х_7.jpg
2024-10-08 15:57:45,420 - Not Found: /media/Volkswagen_Terramont_Х_9.jpg
2024-10-08 15:57:45,427 - Not Found: /media/Volkswagen_Terramont_Х_8.jpg
2024-10-08 15:57:45,438 - Not Found: /media/Volkswagen_Terramont_Х_10.jpg
2024-10-08 15:58:48,378 - Not Found: /media/Volkswagen_Terramont_Х_1.jpg
2024-10-08 15:58:48,393 - Not Found: /media/Volkswagen_Terramont_Х_2.jpg
2024-10-08 15:58:48,397 - Not Found: /media/Volkswagen_Terramont_Х_3.jpg
2024-10-08 15:58:48,402 - Not Found: /media/Volkswagen_Terramont_Х_6.jpg
2024-10-08 15:58:48,415 - Not Found: /media/Volkswagen_Terramont_Х_5.jpg
2024-10-08 15:58:48,426 - Not Found: /media/Volkswagen_Terramont_Х_4.jpg
2024-10-08 15:58:48,485 - Not Found: /media/Volkswagen_Terramont_Х_10.jpg
2024-10-08 15:58:48,493 - Not Found: /media/Volkswagen_Terramont_Х_8.jpg
2024-10-08 15:58:48,505 - Not Found: /media/Volkswagen_Terramont_Х_7.jpg
2024-10-08 15:58:48,513 - Not Found: /media/Volkswagen_Terramont_Х_9.jpg
2024-10-08 15:58:49,019 - Not Found: /media/Volkswagen_Terramont_Х_3.jpg
2024-10-08 15:58:49,020 - Not Found: /media/Volkswagen_Terramont_Х_1.jpg
2024-10-08 15:58:49,030 - Not Found: /media/Volkswagen_Terramont_Х_2.jpg
2024-10-08 15:58:49,042 - Not Found: /media/Volkswagen_Terramont_Х_4.jpg
2024-10-08 15:58:49,043 - Not Found: /media/Volkswagen_Terramont_Х_5.jpg
2024-10-08 15:58:49,051 - Not Found: /media/Volkswagen_Terramont_Х_6.jpg
2024-10-08 15:58:49,063 - Not Found: /media/Volkswagen_Terramont_Х_7.jpg
2024-10-08 15:58:49,071 - Not Found: /media/Volkswagen_Terramont_Х_8.jpg
2024-10-08 15:58:49,089 - Not Found: /media/Volkswagen_Terramont_Х_9.jpg
2024-10-08 15:58:49,092 - Not Found: /media/Volkswagen_Terramont_Х_10.jpg
2024-10-08 16:50:53,476 - /media/aa/A/rg/order/tasks.py changed, reloading.
2024-10-08 16:52:53,181 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-08 16:53:11,231 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-08 16:53:47,376 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-08 16:54:01,353 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-08 16:54:38,836 - /media/aa/A/rg/order/views.py changed, reloading.
2024-10-08 16:58:15,926 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-08 16:58:51,122 - /media/aa/A/rg/cars/forms_generator.py changed, reloading.
2024-10-08 16:59:08,049 - Mail to manager sent successfully
2024-10-08 17:06:12,029 - Not Found: /favicon.ico
2024-10-08 17:06:31,563 - /media/aa/A/rg/order/urls.py changed, reloading.
2024-10-08 17:07:41,704 - /media/aa/A/rg/order/urls.py changed, reloading.
2024-10-08 17:08:05,804 - /media/aa/A/rg/order/urls.py changed, reloading.
2024-10-08 17:08:40,769 - /media/aa/A/rg/rg/urls.py changed, reloading.
2024-10-08 17:09:00,628 - /media/aa/A/rg/order/urls.py changed, reloading.
2024-10-08 17:09:26,630 - /media/aa/A/rg/order/urls.py changed, reloading.
2024-10-08 17:10:22,262 - /media/aa/A/rg/order/models.py changed, reloading.
2024-10-08 17:11:16,983 - /media/aa/A/rg/order/urls.py changed, reloading.
2024-10-08 17:11:47,155 - /media/aa/A/rg/order/urls.py changed, reloading.
2024-10-08 17:12:00,135 - /media/aa/A/rg/order/urls.py changed, reloading.
2024-10-08 17:12:18,595 - Mail to manager sent successfully
2024-10-08 17:13:41,345 - /media/aa/A/rg/order/urls.py changed, reloading.
2024-10-08 17:20:19,174 - /media/aa/A/rg/cars/views.py changed, reloading.
2024-10-08 17:20:35,127 - /media/aa/A/rg/cars/views.py changed, reloading.
2024-10-08 17:21:38,119 - /media/aa/A/rg/cars/views.py changed, reloading.
2024-10-08 17:22:18,358 - Internal Server Error: /19/
Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/aa/A/rg/cars/views.py", line 73, in the_car
    new_cars = Cars.objects.filter(status=1)
NameError: name 'Cars' is not defined
2024-10-08 17:22:41,245 - /media/aa/A/rg/cars/views.py changed, reloading.
2024-10-08 17:56:30,805 - Internal Server Error: /19/
Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/engine.py", line 214, in select_template
    raise TemplateDoesNotExist(", ".join(not_found))
django.template.exceptions.TemplateDoesNotExist: banner_guarantee_insurance.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/aa/A/rg/cars/views.py", line 87, in the_car
    return render(request, 'cars/the_car.html', context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 109, in render
    reraise(exc, self.backend)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: banner_guarantee_insurance.html
2024-10-08 17:56:44,414 - Internal Server Error: /19/
Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/aa/A/rg/cars/views.py", line 87, in the_car
    return render(request, 'cars/the_car.html', context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/engine.py", line 208, in select_template
    return self.get_template(template_name)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 573, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 23: 'static'. Did you forget to register or load this tag?
2024-10-08 17:56:58,668 - Internal Server Error: /19/
Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 510, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/aa/A/rg/cars/views.py", line 87, in the_car
    return render(request, 'cars/the_car.html', context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/engine.py", line 208, in select_template
    return self.get_template(template_name)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 512, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 573, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 23: 'static'. Did you forget to register or load this tag?
2024-10-08 17:57:21,557 - Internal Server Error: /19/
Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/aa/A/rg/cars/views.py", line 87, in the_car
    return render(request, 'cars/the_car.html', context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/aa/.local/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/aa/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'working' not found. 'working' is not a valid view function or pattern name.
2024-10-08 17:57:23,604 - Internal Server Error: /19/
Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/aa/A/rg/cars/views.py", line 87, in the_car
    return render(request, 'cars/the_car.html', context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/aa/.local/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/aa/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'working' not found. 'working' is not a valid view function or pattern name.
2024-10-08 17:57:23,729 - Not Found: /favicon.ico
2024-10-08 22:34:07,031 - Internal Server Error: /service/
Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 199, in render
    template = context.template.engine.select_template(template_name)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/engine.py", line 214, in select_template
    raise TemplateDoesNotExist(", ".join(not_found))
django.template.exceptions.TemplateDoesNotExist: banner_catalog_feedback.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/aa/A/rg/main/views.py", line 88, in service
    return render(request, 'main/service.html', context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 109, in render
    reraise(exc, self.backend)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 130, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: banner_catalog_feedback.html
2024-10-08 22:34:17,539 - Internal Server Error: /service/
Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/urls/base.py", line 71, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'car'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/media/aa/A/rg/main/views.py", line 88, in service
    return render(request, 'main/service.html', context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/base.py", line 969, in render_annotated
    return self.render(context)
  File "/home/aa/.local/lib/python3.10/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/aa/.local/lib/python3.10/site-packages/django/urls/base.py", line 82, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'car' is not a registered namespace
